use crate::animation_state::AnimationState;
#[derive(Clone, Debug, Default)]
pub struct StartingCrewMember {
    pub race: String,
    pub name: String,
}

#[derive(Default, Debug)]
pub struct CrewMember {
    pub name: String,
    pub race: String,
    pub drone: bool,
    pub hp: i32,
    pub x_cord: i32,
    pub y_cord: i32,
    pub room_number: i32,
    pub room_tile: i32,
    pub player_controlled: bool,
    pub clone_ready: i32,
    pub death_order: i32,
    pub sprite_tint_indeces: Vec<i32>,
    pub mind_controlled: bool,
    pub saved_room_square: i32,
    pub saved_room_id: i32,
    pub pilot_skill: i32,
    pub engine_skill: i32,
    pub shield_skill: i32,
    pub weapon_skill: i32,
    pub repair_skill: i32,
    pub combat_skill: i32,
    pub male: bool,
    pub repairs: i32,
    pub kills: i32,
    pub evasions: i32,
    pub jumps_survived: i32,
    pub skill_masteries_earned: i32,
    pub stun_ticks: i32,
    pub health_boost: i32,
    pub clonebay_priority: i32,
    pub damage_boost: i32,
    pub unkown_data_block_1: i32,
    pub universal_death_count: i32,
    pub pilot_mastery_one: bool,
    pub pilot_mastery_two: bool,
    pub engine_mastery_one: bool,
    pub engine_mastery_two: bool,
    pub shield_mastery_one: bool,
    pub shield_mastery_two: bool,
    pub weapon_mastery_one: bool,
    pub weapon_mastery_two: bool,
    pub repair_mastery_one: bool,
    pub repair_mastery_two: bool,
    pub combat_mastery_one: bool,
    pub combat_mastery_two: bool,
    pub unkown_data_block_2: i32,
    pub teleport_animation: AnimationState,
    pub unkown_data_block_3: i32,
    //only used if race is crystal
    pub lockdown_recharge_ticks: i32,
    pub lockdown_recharge_goal: i32,
    pub unkown_data_block_4: i32,
}
